[build]
  command = "pip install -r requirements.txt && python -c \"from app import app; import uvicorn; uvicorn.run(app, host='0.0.0.0', port=8080)\""
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
